### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by nickdesaulniers** [gpac/node-gpac-dash#4]
```
➜  buildz git:(master) ✗ node /Users/Nicholas/mozilla/node-gpac-dash/gpac-dash.js -segment-marker eods -chunk-media-segments -cors
...
[15:54:21.887] File output/v1_43_gpac.m4s, sending mdat data from 0 to 2616143 in 355 ms (total_sent: 2616144) at utc 1445554461887
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at sendAndUpdateBuffer (/Users/Nicholas/mozilla/node-gpac-dash/gpac-dash.js:92:11)
    at readFromBufferAndSendBoxes (/Users/Nicholas/mozilla/node-gpac-dash/gpac-dash.js:214:13)
    at sendFragmentedFile (/Users/Nicholas/mozilla/node-gpac-dash/gpac-dash.js:274:23)
    at Parameters.watchListener (/Users/Nicholas/mozilla/node-gpac-dash/gpac-dash.js:357:3)
    at FSWatcher.emit (events.js:110:17)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1159:12)
```

I'm trying to understand, it looks like on file change, we're assuming we have a response in flight?

**Comment by nickdesaulniers** [comment]
note this was on my branch #3, I could have regressed something.

**Comment by nickdesaulniers** [comment]
yep, fixed
