### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by jalowin** [gpac/node-gpac-dash#7]
I try to run this application but I get this error

node gpac-dash.js
[18:08:30.218] Runnning /usr/local/nginx/html/dash/gpac-dash.js using /usr/bin/nodejs version v0.10.25 in /usr/local/nginx/html/dash
[18:08:30.224] Server running on 127.0.0.1:8000 in normal mode

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRINUSE
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1039:14)
    at listen (net.js:1061:10)
    at net.js:1143:9
    at dns.js:72:18
    at process._tickCallback (node.js:415:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:902:3

Thanks for all

best regards

**Comment by jeanlf** [comment]
you likely have an other program using the same address/port

**Comment by ulrichghislain** [comment]
Hello 
i'm a beginner of node-gpac-dash 
i want to nkow how could i install it?
and command

help me please

**Comment by cconcolato** [comment]
@ulrichghislain simply run the node-gpac.js file with node as documented in the [README](https://github.com/gpac/node-gpac-dash/blob/master/README.md)
